### ISSUE TITLE
an exception was raised: (FunctionClauseError) no function clause matching in :lists.reverse/1

### ISSUE THREAD

**Issue by guofei** [mgwidmann/scrivener_html#20]
Hi, I added {:scrivener_html, "~> 1.0"} to mix.exs and then run phoenix.server, it shows these errors:

```
Server: localhost:4000 (http)
Request: GET /messages
 ** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :lists.reverse/1
```

diff:

```
diff --git a/mix.exs b/mix.exs
index a6e360c..5cb25da 100644
--- a/mix.exs
+++ b/mix.exs
      {:postgrex, "~> 0.11"},
-     {:scrivener, "~> 1.0"}]
+     {:scrivener, "~> 1.0"},
+     {:scrivener_html, "~> 1.0"}]
   end

diff --git a/mix.lock b/mix.lock
index f8e42f2..3aa7fa9 100644
--- a/mix.lock
+++ b/mix.lock
+  "scrivener_html": {:hex, :scrivener_html, "1.1.0"......
```

**Comment by mgwidmann** [comment]
Huh odd as 1.1 was just a version bump to support Phoenix 1.2

Can you post more of the stack trace?

**Comment by guofei** [comment]
error message:

```
[error] #PID<0.434.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /messages
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :lists.reverse/1
        (stdlib) lists.erl:146: :lists.reverse([{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]\
} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n     \
     test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{\
:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n   \
     "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\
\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, [{:safe, ["" | "\n          test\n        "]} | {:cont, []}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}])
        (my_app) web/templates/message/index.html.eex:14: MyApp.MessageView."index.html"/1
        (my_app) web/templates/layout/app.html.eex:84: MyApp.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (my_app) web/controllers/message_controller.ex:1: MyApp.MessageController.action/2
        (my_app) web/controllers/message_controller.ex:1: MyApp.MessageController.phoenix_controller_pipeline/2
        (my_app) lib/phoenix/router.ex:261: MyApp.Router.dispatch/2
        (my_app) web/router.ex:1: MyApp.Router.do_call/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
        (my_app) lib/plug/debugger.ex:93: MyApp.Endpoint."call (overridable 3)"/2
        (my_app) lib/phoenix/endpoint/render_errors.ex:34: MyApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

controller:

```
  def index(conn, params) do
    query = from m in Message,
      join: r in UserRoom, on: m.room_id == r.room_id,
      where: r.id == ^conn.assigns.current_user.id,
      preload: [:from, :to],
      order_by: [desc: :inserted_at]
    messages = Repo.paginate(query, params)
    render(conn, "index.html", messages: messages)
  end
```

templete:

```
    <table class="">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">From</th>
          <th class="mdl-data-table__cell--non-numeric">To</th>
          <th class="mdl-data-table__cell--non-numeric">Message</th>
          <th class="mdl-data-table__cell--non-numeric">Created At</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for message <- @messages do %>
          test
        <% end %>
      </tbody>
    </table>
```

**Comment by mgwidmann** [comment]
Which line is line 14 in the view?

I dont see any call to `pagination_links` so I'm not sure how this package could have affected your app.

**Comment by guofei** [comment]
line 14 is
```
        <%= for message <- @messages do %>
```

I just added  {:scrivener_html, "~> 1.0"} to mix.exs, then it crashed.

**Comment by guofei** [comment]
It fixed if I change scrivener_html/lib/scrivener/html.ex

from

```
# Must do this until Scrivener adds @derive [Enumerable, Access]
defimpl Enumerable, for: Scrivener.Page do
  def reduce(pages, acc, fun), do: Enum.reduce(pages.entries || [], acc, fun)
  def member?(pages, page), do: page in pages.entries
  def count(pages), do: length(pages.entries)
end
```

to
```
# Must do this until Scrivener adds @derive [Enumerable, Access]
defimpl Enumerable, for: Scrivener.Page do
  def reduce(pages, acc, fun), do: Enumerable.reduce(pages.entries || [], acc, fun)
  def member?(pages, page), do: page in pages.entries
  def count(pages), do: length(pages.entries)
end
```

**Comment by mgwidmann** [comment]
oh huh, I guess this is related to #21

**Comment by mgwidmann** [comment]
Would you try with either the recently released version `1.1.1` or `1.0.11`

**Comment by guofei** [comment]
1.1.1 is ok.
Thank you very much!

**Comment by guofei** [comment]
1.0.11 is also ok.
